'''
data file:

'''

input_text = '''

Natural factors
The natural factors that affect the human sex ratio are an active area of scientific research. Over 1000 articles have been published in various journals. Two of the often cited reviews of scientific studies on human sex ratio are by W. H. James.[25][26] The scientific studies are based on extensive birth and death records in Africa, the Americas, Asia, Australia, and Europe. A few of these studies extend to over 100 years of yearly human sex ratio data for some countries. These studies suggest that the human sex ratio, both at birth and as a population matures, can vary significantly according to a large number of factors, such as paternal age, maternal age, plural birth, birth order, gestation weeks, race, parent's health history, and parent's psychological stress. Remarkably, the trends in human sex ratio are not consistent across countries at a given time, or over time for a given country. In economically developed countries, as well as developing countries, these scientific studies have found that the human sex ratio at birth has historically varied between 0.94 and 1.15 for natural reasons.

In a scientific paper published in 2008,[11] James states that conventional assumptions have been:

there are equal numbers of X and Y chromosomes in mammalian sperm
X and Y stand equal chance of achieving conception
therefore equal numbers of male and female zygotes are formed
therefore any variation of sex ratio at birth is due to sex selection between conception and birth.
James cautions that available scientific evidence stands against the above assumptions and conclusions. He reports that there is an excess of males at birth in almost all human populations, and the natural sex ratio at birth is usually between 1.02 and 1.08. However the ratio may deviate significantly from this range for natural reasons.

A 1999 scientific paper published by Jacobsen reported the sex ratio for 815,891 children born in Denmark between 1980–1993.[27] They studied the birth records to identify the effects of multiple birth, birth order, age of parents and the sexes of preceding siblings on the proportion of males using contingency tables, chi-squared tests and regression analysis. The secondary sex ratio decreased with increasing number of children per plural birth and with paternal age, whereas no significant independent effect was observed for maternal age, birth order, or other natural factors.

A 2009 research paper published by Branum et al. reports the sex ratio derived from data in United States birth records over a 25-year period (1981–2006).[28] This paper reports that the sex ratio at birth for the white ethnic group in the United States was 1.04 when the gestational age was 33–36 weeks, but 1.15 for gestational ages of less than 28 weeks, 28–32 weeks, and 37 or more weeks. This study also found that the sex ratios at birth in the United States, between 1981–2006, were lower in both black and Hispanic ethnic groups when compared with white ethnic group.

The relationship between natural factors and human sex ratio at birth, and with aging, remains an active area of scientific research.

Environmental factors
Effects of climate change
Various scientists have examined the question whether human birth sex ratios have historically been affected by environmental stressors such as climate change and global warming. Catalano et al. report that cold weather is an environmental stressor, and women subjected to colder weather abort frail male fetuses in greater proportion, thereby lowering birth sex ratios. But cold weather stressors also extend male longevity, thereby raising the human sex ratio at older ages.[29] The Catalano team finds that a 1 °C increase in annual temperature predicts one more male than expected for every 1,000 females born in a year.

Helle et al. have studied 138 years of human birth sex ratio data, from 1865 to 2003. They find an increased excess of male births during periods of exogenous stress (World War II) and during warm years. In the warmest period over the 138 years, the birth sex ratio peaked at about 1.08 in northern Europe.[30]

Effects of gestation environment
Causes of stress during gestation, such as maternal malnutrition[31] generally appear to increase fetal deaths particularly among males,[29] resulting in a lower boy to girl ratio at birth. Also, higher incidence of Hepatitis B virus in populations is believed to increase the male to female sex ratio, while some unexplained environmental health hazards are thought to have the opposite effect.[32]

The effects of gestational environment on human sex ratio are complicated and unclear, with numerous conflicting reports. For example, Oster et al. examined a data set of 67,000 births in China, 15 percent of whom were Hepatitis B carriers. They found no effect on birth sex ratio from Hepatitis B presence in either the mothers or fathers.[33]

Effects of chemical pollution

A comparison of the structures of the natural hormone estradiol (left) and one of the nonyl-phenols (right), an endocrine disruptor
A 2007 survey by the Arctic Monitoring and Assessment Program noted abnormally low sex ratios in Russian Arctic villages and Inuit villages in Greenland and Canada, and attributed this imbalance to high levels of endocrine disruptors in the blood of inhabitants, including PCBs and DDT. These chemicals are believed to have accumulated in the tissues of fish and animals that make up the bulk of these populations' diets.[34] However, as noted in the Social factors section below, it is important to exclude alternative explanations, including social ones, when examining large human populations whose composition by ethnicity and race may be changing.

A 2008 report provides further evidence of effects of feminizing chemicals on male development in each class of vertebrate species as a worldwide phenomenon, possibly leading to a decline in the sex ratio in humans and a possible decline in sperm counts.[35] Out of over 100,000 recently introduced chemicals, 99% are poorly regulated.[35]

Other factors that could possibly affect the sex ratio include:

Social status of the mother, known to be a factor in influencing the sex ratio of certain animals such as swine,[36] but apparently not in humans.[37]
Whether the mother smokes.[38]
Whether the mother has a partner or other support network,[39] although this correlation is widely considered[by whom?] to be the result of an unknown third factor.
Latitude, with countries near the equator producing more females than near the poles.[40]
Other scientific studies suggest that environmental effects on human sex ratio at birth are either limited or not properly understood. For example, a research paper published in 1999, by scientists from Finland’s National Public Health Institute, reports the effect of environmental chemicals and changes in sex ratio over 250 years in Finland.[41] This scientific team evaluated whether Finnish long-term data are compatible with the hypothesis that the decrease in the ratio of male to female births in industrial countries is caused by environmental factors. They analyzed the sex ratio of births from the files of Statistics Finland and all live births in Finland from 1751 to 1997. They found an increase in the proportion of males from 1751 to 1920; this was followed by a decrease and interrupted by peaks in births of males during and after World War I and World War II. None of the natural factors such as paternal age, maternal age, age difference of parents, birth order could explain the time trends. The scientists found that the peak ratio of male proportion precedes the period of industrialization or the introduction of pesticides or hormonal drugs, rendering a causal association between environmental chemicals and human sex ratio at birth unlikely. Moreover, these scientists claim that the trends they found in Finland are similar to those observed in other countries with worse pollution and much greater pesticide use.

Some studies have found that certain kinds of environmental pollution, in particular dioxins leads to higher rates of female births.[42][43]

Social factors

Sign in an Indian hospital stating that prenatal sex determination is not done there and is illegal
Sex-selective abortion and infanticide are thought to significantly skew the naturally occurring ratio in some populations, such as China, where the introduction of ultrasound scans in the late 1980s has led to a birth sex ratio (males to females) of 1.181 (2010 official census data for China).[44] The 2011 India census reports India's sex ratio in 0–6 age bracket at 1.088.[45] The 2011 birth sex ratios for China and India are significantly above the mean ratio recorded in the United States from 1940 through 2002 (1.051); however, their birth sex ratios are within the 0.98–1.14 range observed in the United States for significant ethnic groups over the same time period.[24]:10 Along with Asian countries, a number of European, Middle East, and Latin American countries have recently reported high birth sex ratios in the 1.06 to 1.14 range. High birth sex ratios, some claim, may be caused in part by social factors.

Reported sex ratios at birth, outside the typical range of 1.03 to 1.07, thus call for an explanation of some kind.

Another hypothesis has been inspired by the recent and persistent high birth sex ratios observed in Georgia and Armenia—both predominantly Orthodox Christian societies—and Azerbaijan, a predominantly Muslim society. Since their independence from Soviet Union, the birth sex ratio in these Caucasus countries has risen sharply to between 1.11 and 1.20, some of world's highest. Mesle et al. consider the hypothesis that the high birth sex ratio may be because of the social trend of more than two children per family, and birth order possibly affects the sex ratio in this region of the world. They also consider the hypothesis that sons are preferred in these countries of the Caucasus, the spread of scans and there being a practice of sex-selective abortion; however, the scientists admit that they do not have definitive proof that sex-selective abortion is actually happening or that there are no natural reasons for the persistently high birth sex ratios.[46]

As an example of how the social composition of a human population may produce unusual changes in sex ratios, in a study in several counties of California where declining sex ratios had been observed, Smith and Von Behren observe "In the raw data, the male birth proportion is indeed declining. However, during this period, there were also shifts in demographics that influence the sex ratio. Controlling for birth order, parents' age, and race/ethnicity, different trends emerged. White births (which account for over 80%) continued to show a statistically significant decline, while other racial groups showed non-statistically significant declines (Japanese, Native American, other), little or no change (black), or an increase (Chinese). Finally, when the white births were divided into Hispanic and non-Hispanic (possible since 1982), it was found that both white subgroups suggest an increase in male births." They concluded, "that the decline in male births in California is largely attributable to changes in demographics."[47]

Early marriage and parents' age
Several studies have examined human birth sex ratio data to determine whether there is a natural relationship between the age of mother or father and the birth sex ratio. For example, Ruder has studied 1.67 million births in 33 states in the United States to investigate the effect of parents' ages on birth sex ratios.[48] Similarly, Jacobsen et al. have studied 0.82 million births in Denmark with the same goal.[49] These scientists find that maternal age has no statistically significant role on the human birth sex ratio. However, they report a significant effect of paternal age. Significantly more male babies were born per 1000 female babies to younger fathers than to older fathers. These studies suggest that social factors such as early marriage and bear their children young may play a role in raising birth sex ratios in certain societies.[50]

Data sources and data quality issues
Reported sex ratios at birth for some human populations may be influenced not only by cultural preferences and social practices that favor the birth or survival of one sex over the other but also by incomplete or inaccurate reporting or recording of the births or the survival of infants.[citation needed] Even what constitutes a live birth or infant death may vary from one population to another. For example, for most of the 20th century in Russia (and the Soviet Union), extremely premature newborns (less than 28 weeks gestational age, or less than 1000 grams in weight, or less than 35 centimeters in length) were not counted as a live birth until they had survived 7 days; and if that infant died in those first 168 hours it would not be counted as an infant death. This led to serious underreporting of the infant mortality rate (by 22% to 25%) relative to standards recommended by the World Health Organization.[51]


Chinese One Child Policy propaganda from 1982
When unusual sex ratios at birth (or any other age) are observed, it is important to consider misreporting, misrecording, or under-registration of births or deaths as possible reasons. Some researchers have in part attributed the high male to female sex ratios reported in mainland China in the last 25 years to the underreporting of the births of female children after the implementation of the one-child policy, though alternative explanations are now generally more widely accepted, including above all the use of ultrasound technology and sex-selective abortion of female fetuses and, probably to a more limited degree, neglect or in some cases infanticide of females. In the case of China, because of deficiencies in the vital statistics registration system, studies of sex ratios at birth have relied either on special fertility surveys, whose accuracy depends on full reporting of births and survival of both male and female infants, or on the national population census from which both birth rates and death rates are calculated from the household's reporting of births and deaths in the 18 months preceding the census.[52] To the extent that this underreporting of births or deaths is sex-selective, both fertility surveys and censuses may inaccurately reflect the actual sex ratios at birth.[53]

Economic factors
Catalano has examined the hypothesis that population stress induced by a declining economy reduces the human sex ratio. He compared the sex ratio in East and West Germany for the years 1946 to 1999, with genetically similar populations. The population stressors theory predicts that the East German sex ratio should have been lower in 1991 when East Germany's economy collapsed than expected from its previous years. Furthermore, the theory suggests that East German birth sex ratios should generally be lower than the observed sex ratio in West Germany for the same years, over time. According to Catalano's study, the birth sex ratio data from East Germany and West Germany over 45 years support the hypothesis. The sex ratio in East Germany was also at its lowest in 1991. According to Catalano study, assuming women in East Germany did not opt to abort male more than female, the best hypothesis is that a collapsing economy lowers the human birth sex ratio, while a booming economy raises the birth sex ratio. Catalano notes that these trends may be related to the observed trend of elevated incidences of very low birth weight from maternal stress, during certain macroeconomic circumstances.[54]

Other gestational factors
A research group led by Ein-Mor reported that sex ratio does not seem to change significantly with either maternal or paternal age. Neither gravidity nor parity seem to affect the male-to-female ratio.[55] However, there is a significant association of sex ratio with the length of gestation.[55] These Ein-mor conclusions have been disputed. For example, James suggested[56] that Ein-Mor results are based on some demographic variables and a small data set, a broader study of variables and larger population set suggests human sex ratio shows substantial variation for various reasons and different trend effects of length of gestation than those reported by Ein-Mor. In another study, James has offered the hypothesis that human sex ratios, and mammalian sex ratios in general, are causally related to the hormone levels of both parents at the time of conception.[11] This hypothesis is yet to be tested and proven true or false over large population sets.


Gender imbalance in Bahrain caused by policies that restrict female spouses and children of immigrant workers
Gender imbalance
Gender imbalance is a disparity between males and females in a population. As stated above, males usually exceed females at birth but subsequently experience different mortality rates due to many possible causes such as differential natural death rates, war casualties, and deliberate gender control.

According to Nicholas Kristof and Sheryl WuDunn, two Pulitzer Prize-winning reporters for the New York Times, violence against women is causing gender imbalances in many developing countries.[57] They detail sex-selective infanticide in the developing world, particularly in China, India and Pakistan.[57]

Commonly, countries with gender imbalances have three characteristics in common. The first is a rapid decline in fertility, either because of preference for smaller families or to comply with their nation's population control measures. Second, there is pressure for women to give birth to sons, often because of cultural preferences for male heirs. Third, families have widespread access to technology to selectively abort female fetuses.[58]

As a contributing measure to gender imbalance in developing countries, Kristof and WuDunn's[57] best estimate is that a girl in India, from 1 to 5 years of age, dies from discrimination every four minutes (132,000 deaths per year); that 39,000 girls in China die annually, within the first year of life, because parents did not give girls the same medical care and attention that boys received. The authors describe similar gender discrimination and gendercide in Congo, Kenya, Pakistan, Iraq, Bahrain, Thailand and many other developing countries.

Some of the factors suggested as causes of the gender imbalance are warfare (excess of females, notably in the wake of WWI in western Europe, and WWII, particularly in the Soviet Union); sex-selective abortion and infanticide (excess of males, notably in China as a result of the one-child policy, or in India); and large-scale migration, such as that by male labourers unable to bring their families with them (as in Qatar and other Gulf countries[59]). Gender imbalance may result in the threat of social unrest, especially in the case of an excess of low-status young males unable to find spouses,[60] and being recruited into the service of militaristic political factions. Economic factors such as male-majority industries and activities like the petrochemical, agriculture, engineering, military, and technology also have created a male gender imbalance in some areas dependent on one of these industries. Conversely, the entertainment, banking, tourism, fashion, and service industries may have resulted in a female-majority gender imbalance in some areas dependent on them.[61]

One study[62] found that the male-to-female sex ratio in the German state of Bavaria fell as low as 0.60 after the end of World War II for the most severely affected age cohort (those between 21 and 23 years old in 1946). This same study found that out-of-wedlock births spiked from approximately 10–15% during the inter-war years up to 22% at the end of the war. This increase in out-of-wedlock births was attributed to a change in the marriage market caused by the decline in the sex ratio.


Gender imbalance in Estonia
The Northern Mariana Islands have the highest female ratio with 0.77 males per female. Qatar has the highest male ratio, with 2.87 males/female. For the group aged below 15, Sierra Leone has the highest female ratio with 0.96 males/female, and the Republic of Georgia and the People's Republic of China are tied for the highest male ratio with 1.13 males/female (according to the 2006 CIA World Factbook).

The value for the entire world population is 1.01 males/female, with 1.07 at birth, 1.06 for those under 15, 1.02 for those between 15 and 64, and 0.78 for those over 65.[7]

The "First World" G7 members all have a gender ratio in the range of 0.95–0.98 for the total population, of 1.05–1.07 at birth, of 1.05–1.06 for the group below 15, of 1.00–1.04 for the group aged 15–64, and of 0.70–0.75 for those over 65.

Countries on the Arabian peninsula tend to have a 'natural' ratio of about 1.05 at birth but a very high ratio of males for those over 65 (Saudi Arabia 1.13, Arab Emirates 2.73, Qatar 2.84), indicating either an above-average mortality rate for females or a below-average mortality for males, or, more likely in this case, a large population of aging male guest workers.[citation needed] Conversely, countries of Northern and Eastern Europe (the Baltic states, Belarus, Ukraine, Russia) tend to have a 'normal' ratio at birth but a very low ratio of males among those over 65 (Russia 0.46, Latvia 0.48, Ukraine 0.52); similarly, Armenia has a far above average male ratio at birth (1.17), and a below-average male ratio above 65 (0.67). This effect may be caused by emigration and higher male mortality as result of higher Soviet era deaths; it may also be related to the enormous (by western standards) rate of alcoholism in the former Soviet states.[citation needed] Another possible contributory factor is an aging population, with a higher than normal proportion of relatively elderly people: we recall that due to higher differential mortality rates the ratio of males to females reduces for each year of age.

In the evolutionary biology of sexual reproduction, the operational sex ratio (OSR), is the ratio of sexually competing males that are ready to mate to sexually competing females that are ready to mate,[63][64][65] or alternatively the local ratio of fertilizable females to sexually active males at any given time.[66] Its difference from the physical sex ratio, is that it does not take into account sexually inactive or non-competitive individuals (individuals that do not compete for mates). On occasion, regions with a high male-low female sex ratio, like Alaska, have shown a correlation with a higher rate of reported rape.[67]

Consequences of a high sex ratio

Benjaminites seize wives from Shiloh in this 1860 woodcut by Julius Schnorr von Karolsfeld. They were not enough women available for marriage due to the high losses in the Battle at Gibeah.
There are several social consequences of an imbalanced sex ratio. It may also become a factor in societal and demographic collapse. For example, the native population of Cusco, Peru at the time of the Spanish conquest was stressed by an imbalance in the sex ratio between men and women.[68] High ratios of males make it easier for women to marry, but harder for men.[69] In parts of China and India, there is a 12–15% excess of young men. These men will remain single and will be unable to have families, in societies where marriage is regarded as virtually universal and social status and acceptance depend, in large part, on being married and creating a new family. Analyses of how sex ratio imbalances affect personal consumption and intra-household distribution were pioneered by Gary Becker, Shoshana Grossbard-Shechtman,[70][71] and Marcia Guttentag and Paul Secord.[72] High ratios of males have a positive effect on marital fertility and women's share of household consumption and negative effects on non-marital cohabitation and fertility and women's labor supply. It has been shown that variation in sex ratio over time is inversely related to married women's labor supply in the U.S.[73][74]

An additional problem is that many of these men are of low socioeconomic class with limited education. When there is a shortage of women in the marriage market, the women can "marry up",
inevitably leaving
the least desirable men with no marriage prospects. In many communities today, there are growing numbers of young men who come from lower classes who
are marginalized because of lack of family prospects and the fact that they have little outlet for sexual energy. There is evidence that this situation will lead to increased
levels of antisocial behavior and violence and will ultimately present a threat to the stability and security of society.[75] '''
